import { ImageSourcePropType } from 'react-native';

export interface Product {
  id: string;
  name: string;
  brand?: string;
  category: string;
  price: number;
  originalPrice?: number;
  rating: number;
  reviews?: number;
  deliveryTime?: number;
  image?: ImageSourcePropType;
  imageUrl?: string;
  description?: string;
  warranty?: string | null;
  returnDays?: number;
  stock?: number;
}

// Medical-only local fallback products (used when Firestore is unavailable)
export const PRODUCTS: Product[] = [
  // ── Medicines ──────────────────────────────────────────────
  {
    id: '1',
    name: 'Paracetamol 500mg',
    brand: 'GENERIC',
    category: 'Medicines',
    price: 25,
    originalPrice: 30,
    rating: 4.8,
    reviews: 245,
    deliveryTime: 12,
    image: require('@/assets/ProductImage/paracetamol.jpg'),
    description: 'Effective pain reliever and fever reducer. Pack of 10 tablets.',
    warranty: null,
    returnDays: 7,
    stock: 50,
  },
  {
    id: '2',
    name: 'Dettol Hand Sanitizer 500ml',
    brand: 'DETTOL',
    category: 'Medicines',
    price: 50,
    originalPrice: 60,
    rating: 4.5,
    reviews: 567,
    deliveryTime: 10,
    image: require('@/assets/ProductImage/Hand senitizer.jpg'),
    description: 'Kills 99.9% of germs without water. 500ml bottle.',
    warranty: null,
    returnDays: 14,
    stock: 100,
  },
  {
    id: '4',
    name: 'Cough Syrup 150ml',
    brand: 'BENADRYL',
    category: 'Medicines',
    price: 120,
    originalPrice: 135,
    rating: 4.3,
    reviews: 189,
    deliveryTime: 15,
    imageUrl: 'https://images.unsplash.com/photo-1584017911766-d451b3d0e843?auto=format&fit=crop&w=500&q=60',
    description: 'Effective relief from dry and wet cough. 150ml bottle.',
    warranty: null,
    returnDays: 7,
    stock: 80,
  },
  {
    id: '7',
    name: 'Antacid Liquid 200ml',
    brand: 'GELUSIL',
    category: 'Medicines',
    price: 110,
    originalPrice: 125,
    rating: 4.2,
    reviews: 143,
    deliveryTime: 14,
    imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5e4b7b25e?auto=format&fit=crop&w=500&q=60',
    description: 'Fast relief from acidity, heartburn and indigestion. 200ml.',
    warranty: null,
    returnDays: 7,
    stock: 45,
  },
  {
    id: '10',
    name: 'ORS Electrolyte Sachets',
    brand: 'ELECTRAL',
    category: 'Medicines',
    price: 45,
    originalPrice: 50,
    rating: 4.6,
    reviews: 302,
    deliveryTime: 10,
    imageUrl: 'https://images.unsplash.com/photo-1631549916768-4119b2e5f926?auto=format&fit=crop&w=500&q=60',
    description: 'Oral rehydration salts for dehydration. Pack of 10 sachets.',
    warranty: null,
    returnDays: 7,
    stock: 200,
  },

  // ── First Aid ──────────────────────────────────────────────
  {
    id: '8',
    name: 'First Aid Bandages (Pack of 20)',
    brand: 'BAND-AID',
    category: 'First Aid',
    price: 55,
    originalPrice: 65,
    rating: 4.5,
    reviews: 421,
    deliveryTime: 10,
    imageUrl: 'https://images.unsplash.com/photo-1583324113626-70df0f4deaab?auto=format&fit=crop&w=500&q=60',
    description: 'Waterproof adhesive bandages for minor cuts and scrapes. Pack of 20.',
    warranty: null,
    returnDays: 14,
    stock: 300,
  },
  {
    id: '11',
    name: 'Antiseptic Cream 30g',
    brand: 'SAVLON',
    category: 'First Aid',
    price: 65,
    originalPrice: 75,
    rating: 4.6,
    reviews: 310,
    deliveryTime: 12,
    imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5e4b7b25e?auto=format&fit=crop&w=500&q=60',
    description: 'Antiseptic cream for cuts, burns and minor wounds. 30g tube.',
    warranty: null,
    returnDays: 14,
    stock: 150,
  },
  {
    id: '12',
    name: 'Sterile Gauze Pads (Pack of 10)',
    brand: 'JOHNSON',
    category: 'First Aid',
    price: 40,
    originalPrice: 50,
    rating: 4.4,
    reviews: 198,
    deliveryTime: 10,
    imageUrl: 'https://images.unsplash.com/photo-1583324113626-70df0f4deaab?auto=format&fit=crop&w=500&q=60',
    description: 'Sterile gauze pads for wound dressing. Pack of 10.',
    warranty: null,
    returnDays: 14,
    stock: 200,
  },
  {
    id: '13',
    name: 'Digital Thermometer',
    brand: 'OMRON',
    category: 'First Aid',
    price: 199,
    originalPrice: 249,
    rating: 4.7,
    reviews: 534,
    deliveryTime: 15,
    imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5e4b7b25e?auto=format&fit=crop&w=500&q=60',
    description: 'Fast and accurate digital thermometer. Beeps when done.',
    warranty: '1 year',
    returnDays: 7,
    stock: 80,
  },

  // ── Vitamins ───────────────────────────────────────────────
  {
    id: '5',
    name: 'Vitamin C 500mg Tablets',
    brand: 'LIMCEE',
    category: 'Vitamins',
    price: 35,
    originalPrice: 42,
    rating: 4.9,
    reviews: 634,
    deliveryTime: 12,
    imageUrl: 'https://images.unsplash.com/photo-1629909613654-28e377c37b09?auto=format&fit=crop&w=500&q=60',
    description: 'Chewable Vitamin C tablets for daily immunity support. Pack of 15.',
    warranty: null,
    returnDays: 7,
    stock: 150,
  },
  {
    id: '14',
    name: 'Vitamin D3 1000 IU',
    brand: 'HEALTHVIT',
    category: 'Vitamins',
    price: 180,
    originalPrice: 220,
    rating: 4.7,
    reviews: 412,
    deliveryTime: 12,
    imageUrl: 'https://images.unsplash.com/photo-1629909613654-28e377c37b09?auto=format&fit=crop&w=500&q=60',
    description: 'Vitamin D3 supplement for bone health and immunity. 60 capsules.',
    warranty: null,
    returnDays: 7,
    stock: 120,
  },
  {
    id: '15',
    name: 'Multivitamin Tablets (30 count)',
    brand: 'REVITAL',
    category: 'Vitamins',
    price: 250,
    originalPrice: 299,
    rating: 4.5,
    reviews: 876,
    deliveryTime: 12,
    imageUrl: 'https://images.unsplash.com/photo-1550572017-094e9f743ceb?auto=format&fit=crop&w=500&q=60',
    description: 'Complete daily multivitamin with minerals. 30 tablets.',
    warranty: null,
    returnDays: 7,
    stock: 200,
  },
  {
    id: '16',
    name: 'Omega-3 Fish Oil 1000mg',
    brand: 'CARBAMIDE',
    category: 'Vitamins',
    price: 320,
    originalPrice: 380,
    rating: 4.6,
    reviews: 290,
    deliveryTime: 14,
    imageUrl: 'https://images.unsplash.com/photo-1629909613654-28e377c37b09?auto=format&fit=crop&w=500&q=60',
    description: 'High-strength Omega-3 for heart and brain health. 60 softgels.',
    warranty: null,
    returnDays: 7,
    stock: 90,
  },

  // ── Pain Relief ────────────────────────────────────────────
  {
    id: '3',
    name: 'Ibuprofen 400mg',
    brand: 'BRUFEN',
    category: 'Pain Relief',
    price: 40,
    originalPrice: 48,
    rating: 4.6,
    reviews: 312,
    deliveryTime: 12,
    imageUrl: 'https://images.unsplash.com/photo-1631549916768-4119b2e5f926?auto=format&fit=crop&w=500&q=60',
    description: 'Anti-inflammatory pain relief. Pack of 10 tablets.',
    warranty: null,
    returnDays: 7,
    stock: 200,
  },
  {
    id: '6',
    name: 'Aspirin 75mg',
    brand: 'CIPLA',
    category: 'Pain Relief',
    price: 20,
    originalPrice: 25,
    rating: 4.2,
    reviews: 198,
    deliveryTime: 12,
    imageUrl: 'https://images.unsplash.com/photo-1550572017-094e9f743ceb?auto=format&fit=crop&w=500&q=60',
    description: 'Low-dose aspirin for pain relief and fever. Pack of 14 tablets.',
    warranty: null,
    returnDays: 7,
    stock: 110,
  },
  {
    id: '9',
    name: 'Vicks VapoRub 50g',
    brand: 'VICKS',
    category: 'Pain Relief',
    price: 85,
    originalPrice: 95,
    rating: 4.7,
    reviews: 876,
    deliveryTime: 12,
    imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5e4b7b25e?auto=format&fit=crop&w=500&q=60',
    description: 'Topical relief from cold, cough and blocked nose. 50g jar.',
    warranty: null,
    returnDays: 7,
    stock: 30,
  },
  {
    id: '17',
    name: 'Volini Pain Relief Spray 100g',
    brand: 'VOLINI',
    category: 'Pain Relief',
    price: 145,
    originalPrice: 165,
    rating: 4.5,
    reviews: 543,
    deliveryTime: 12,
    imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5e4b7b25e?auto=format&fit=crop&w=500&q=60',
    description: 'Fast-acting pain relief spray for muscle and joint pain. 100g.',
    warranty: null,
    returnDays: 7,
    stock: 75,
  },

  // ── Cold & Flu ─────────────────────────────────────────────
  {
    id: '18',
    name: 'Cetirizine 10mg (10 tablets)',
    brand: 'ZYRTEC',
    category: 'Cold & Flu',
    price: 30,
    originalPrice: 38,
    rating: 4.4,
    reviews: 267,
    deliveryTime: 12,
    imageUrl: 'https://images.unsplash.com/photo-1631549916768-4119b2e5f926?auto=format&fit=crop&w=500&q=60',
    description: 'Antihistamine for allergy and cold symptoms. Pack of 10.',
    warranty: null,
    returnDays: 7,
    stock: 180,
  },
  {
    id: '19',
    name: 'Nasal Decongestant Spray',
    brand: 'OTRIVIN',
    category: 'Cold & Flu',
    price: 95,
    originalPrice: 110,
    rating: 4.3,
    reviews: 189,
    deliveryTime: 14,
    imageUrl: 'https://images.unsplash.com/photo-1584017911766-d451b3d0e843?auto=format&fit=crop&w=500&q=60',
    description: 'Fast relief from nasal congestion. 10ml spray bottle.',
    warranty: null,
    returnDays: 7,
    stock: 60,
  },

  // ── Skin Care ──────────────────────────────────────────────
  {
    id: '20',
    name: 'Moisturizing Lotion SPF 30',
    brand: 'CETAPHIL',
    category: 'Skin Care',
    price: 299,
    originalPrice: 349,
    rating: 4.8,
    reviews: 712,
    deliveryTime: 12,
    imageUrl: 'https://images.unsplash.com/photo-1556228578-8c89e6adf883?auto=format&fit=crop&w=500&q=60',
    description: 'Daily moisturizer with SPF 30 sun protection. 100ml.',
    warranty: null,
    returnDays: 14,
    stock: 130,
  },
  {
    id: '21',
    name: 'Calamine Lotion 100ml',
    brand: 'LACTO',
    category: 'Skin Care',
    price: 75,
    originalPrice: 90,
    rating: 4.5,
    reviews: 345,
    deliveryTime: 12,
    imageUrl: 'https://images.unsplash.com/photo-1556228578-8c89e6adf883?auto=format&fit=crop&w=500&q=60',
    description: 'Soothing calamine lotion for rashes, itching and sunburn. 100ml.',
    warranty: null,
    returnDays: 14,
    stock: 95,
  },
];
