import { ImageSourcePropType } from 'react-native';

export interface Product {
  id: string;
  name: string;
  brand?: string;
  category: string;
  price: number;
  originalPrice?: number;
  rating: number;
  reviews?: number;
  deliveryTime: number;
  image: ImageSourcePropType;
  description?: string;
  warranty?: string | null;
  returnDays?: number;
}

// All Products Data
export const PRODUCTS: Product[] = [
  // Existing Products
  {
    id: '1',
    name: 'Paracetamol',
    brand: 'GENERIC',
    category: 'medicines',
    price: 25,
    rating: 4.0,
    reviews: 245,
    deliveryTime: 12,
    image: require('@/assets/ProductImage/paracetamol.jpg'),
    description: 'Effective pain reliever and fever reducer. Pack of 10 tablets.',
    warranty: '1 Year',
    returnDays: 7,
  },
  {
    id: '2',
    name: 'Saras Milk',
    brand: 'SARAS',
    category: 'grocery',
    price: 26,
    originalPrice: 27,
    rating: 4.9,
    reviews: 892,
    deliveryTime: 15,
    image: require('@/assets/ProductImage/sarash milk.avif'),
    description: 'Fresh and pure milk, 1 liter. Rich in calcium and vitamins.',
    warranty: null,
    returnDays: 3,
  },
  {
    id: '3',
    name: 'Hand Sanitizer Dettol',
    brand: 'DETTOL',
    category: 'beauty',
    price: 30,
    rating: 4.5,
    reviews: 567,
    deliveryTime: 10,
    image: require('@/assets/ProductImage/Hand senitizer.jpg'),
    description: '99.9% germ protection. 500ml bottle.',
    warranty: null,
    returnDays: 14,
  },
  {
    id: '4',
    name: 'Bru Coffee',
    brand: 'BRU',
    category: 'grocery',
    price: 18.5,
    originalPrice: 22.0,
    rating: 4.7,
    reviews: 1203,
    deliveryTime: 18,
    image: require('@/assets/ProductImage/Bru coffee.jpg'),
    description: 'Instant premium coffee powder. 100g pack.',
    warranty: null,
    returnDays: 7,
  },
  {
    id: '5',
    name: 'CMF buds pro 2',
    brand: 'NOTHING',
    category: 'electronics',
    price: 45.0,
    originalPrice: 59.0,
    rating: 4.6,
    reviews: 430,
    deliveryTime: 25,
    image: require('@/assets/ProductImage/CMF buds pro 2.jpg'),
    description: 'Wireless earbuds with active noise cancellation.',
    warranty: '1 Year Warranty',
    returnDays: 14,
  },
  {
    id: '6',
    name: 'Dot & Key 10% Vitamin C+E',
    brand: 'DOT & KEY',
    category: 'beauty',
    price: 24.0,
    rating: 4.9,
    reviews: 678,
    deliveryTime: 10,
    image: require('@/assets/ProductImage/serum.webp'),
    description: 'Brightening serum with Vitamin C and E. 30ml.',
    warranty: null,
    returnDays: 14,
  },
  {
    id: '7',
    name: 'RedBull Energy Drink',
    brand: 'REDBULL',
    category: 'grocery',
    price: 2.5,
    rating: 4.5,
    reviews: 892,
    deliveryTime: 14,
    image: require('@/assets/ProductImage/red-bull.avif'),
    description: 'Energy drink 250ml. Gives you wings!',
    warranty: null,
    returnDays: 3,
  },

  // 🏥 MEDICINES (Additional 9)
  {
    id: '8',
    name: 'Ibuprofen Tablets',
    brand: 'Brufen',
    category: 'medicines',
    price: 50,
    rating: 4.3,
    reviews: 340,
    deliveryTime: 12,
    image: require('@/assets/ProductImage/paracetamol.jpg'),
    description: 'Pain relief and anti-inflammatory',
    warranty: null,
    returnDays: 7,
  },
  {
    id: '9',
    name: 'Vitamin C Tablets',
    brand: 'Limcee',
    category: 'medicines',
    price: 120,
    rating: 4.7,
    reviews: 520,
    deliveryTime: 15,
    image: require('@/assets/ProductImage/serum.webp'),
    description: 'Boosts immunity',
    warranty: null,
    returnDays: 10,
  },
  {
    id: '10',
    name: 'Cough Syrup',
    brand: 'Benadryl',
    category: 'medicines',
    price: 90,
    rating: 4.4,
    reviews: 280,
    deliveryTime: 10,
    image: require('@/assets/ProductImage/Hand senitizer.jpg'),
    description: 'Relief from cough and throat irritation',
    warranty: null,
    returnDays: 7,
  },
  {
    id: '11',
    name: 'Antacid Gel',
    brand: 'Gelusil',
    category: 'medicines',
    price: 85,
    rating: 4.2,
    reviews: 210,
    deliveryTime: 12,
    image: require('@/assets/ProductImage/Bru coffee.jpg'),
    description: 'Relief from acidity',
    warranty: null,
    returnDays: 7,
  },
  {
    id: '12',
    name: 'ORS Sachets',
    brand: 'Electral',
    category: 'medicines',
    price: 20,
    rating: 4.6,
    reviews: 450,
    deliveryTime: 8,
    image: require('@/assets/ProductImage/red-bull.avif'),
    description: 'Prevents dehydration',
    warranty: null,
    returnDays: 5,
  },
  {
    id: '13',
    name: 'Calcium Tablets',
    brand: 'Shelcal',
    category: 'medicines',
    price: 150,
    rating: 4.5,
    reviews: 380,
    deliveryTime: 15,
    image: require('@/assets/ProductImage/CMF buds pro 2.jpg'),
    description: 'Supports bone health',
    warranty: null,
    returnDays: 10,
  },
  {
    id: '14',
    name: 'Allergy Tablets',
    brand: 'Cetirizine',
    category: 'medicines',
    price: 60,
    rating: 4.3,
    reviews: 290,
    deliveryTime: 12,
    image: require('@/assets/ProductImage/sarash milk.avif'),
    description: 'Relief from allergies',
    warranty: null,
    returnDays: 7,
  },
  {
    id: '15',
    name: 'Insulin Injection',
    brand: 'NovoRapid',
    category: 'medicines',
    price: 350,
    rating: 4.8,
    reviews: 120,
    deliveryTime: 20,
    image: require('@/assets/ProductImage/paracetamol.jpg'),
    description: 'Used for diabetes control',
    warranty: '2 Year',
    returnDays: 14,
  },
  {
    id: '16',
    name: 'Blood Pressure Tablets',
    brand: 'Amlodipine',
    category: 'medicines',
    price: 200,
    rating: 4.6,
    reviews: 340,
    deliveryTime: 18,
    image: require('@/assets/ProductImage/serum.webp'),
    description: 'Controls high blood pressure',
    warranty: null,
    returnDays: 7,
  },

  // 💄 BEAUTY PRODUCTS (10)
  {
    id: '17',
    name: 'Face Wash',
    brand: 'Himalaya',
    category: 'beauty',
    price: 180,
    rating: 4.4,
    reviews: 650,
    deliveryTime: 10,
    image: require('@/assets/ProductImage/Hand senitizer.jpg'),
    description: 'Cleanses skin deeply',
    warranty: null,
    returnDays: 14,
  },
  {
    id: '18',
    name: 'Moisturizer',
    brand: 'Nivea',
    category: 'beauty',
    price: 250,
    rating: 4.5,
    reviews: 720,
    deliveryTime: 12,
    image: require('@/assets/ProductImage/serum.webp'),
    description: 'Keeps skin hydrated',
    warranty: null,
    returnDays: 14,
  },
  {
    id: '19',
    name: 'Sunscreen SPF 50',
    brand: 'Lotus',
    category: 'beauty',
    price: 350,
    rating: 4.6,
    reviews: 580,
    deliveryTime: 15,
    image: require('@/assets/ProductImage/red-bull.avif'),
    description: 'Protects from UV rays',
    warranty: null,
    returnDays: 14,
  },
  {
    id: '20',
    name: 'Shampoo',
    brand: 'Dove',
    category: 'beauty',
    price: 220,
    rating: 4.5,
    reviews: 890,
    deliveryTime: 10,
    image: require('@/assets/ProductImage/Bru coffee.jpg'),
    description: 'Hair nourishment',
    warranty: null,
    returnDays: 14,
  },
  {
    id: '21',
    name: 'Hair Oil',
    brand: 'Parachute',
    category: 'beauty',
    price: 140,
    rating: 4.7,
    reviews: 750,
    deliveryTime: 10,
    image: require('@/assets/ProductImage/sarash milk.avif'),
    description: 'Strengthens hair',
    warranty: null,
    returnDays: 14,
  },
  {
    id: '22',
    name: 'Lip Balm',
    brand: 'Maybelline',
    category: 'beauty',
    price: 120,
    rating: 4.4,
    reviews: 420,
    deliveryTime: 8,
    image: require('@/assets/ProductImage/Hand senitizer.jpg'),
    description: 'Moisturizes lips',
    warranty: null,
    returnDays: 7,
  },
  {
    id: '23',
    name: 'Body Lotion',
    brand: 'Vaseline',
    category: 'beauty',
    price: 300,
    rating: 4.5,
    reviews: 620,
    deliveryTime: 12,
    image: require('@/assets/ProductImage/serum.webp'),
    description: 'Soft and smooth skin',
    warranty: null,
    returnDays: 14,
  },
  {
    id: '24',
    name: 'Face Cream',
    brand: "Pond's",
    category: 'beauty',
    price: 280,
    rating: 4.4,
    reviews: 550,
    deliveryTime: 12,
    image: require('@/assets/ProductImage/CMF buds pro 2.jpg'),
    description: 'Brightens skin',
    warranty: null,
    returnDays: 14,
  },
  {
    id: '25',
    name: 'Deodorant',
    brand: 'Axe',
    category: 'beauty',
    price: 199,
    rating: 4.3,
    reviews: 480,
    deliveryTime: 10,
    image: require('@/assets/ProductImage/red-bull.avif'),
    description: 'Long lasting fragrance',
    warranty: null,
    returnDays: 7,
  },
  {
    id: '26',
    name: 'Makeup Kit',
    brand: 'Lakme',
    category: 'beauty',
    price: 999,
    rating: 4.6,
    reviews: 380,
    deliveryTime: 15,
    image: require('@/assets/ProductImage/paracetamol.jpg'),
    description: 'Complete makeup set',
    warranty: null,
    returnDays: 14,
  },

  // 🛒 GROCERIES (10)
  {
    id: '27',
    name: 'Basmati Rice 1kg',
    brand: 'India Gate',
    category: 'grocery',
    price: 120,
    rating: 4.5,
    reviews: 820,
    deliveryTime: 20,
    image: require('@/assets/ProductImage/Bru coffee.jpg'),
    description: 'Premium quality rice',
    warranty: null,
    returnDays: 7,
  },
  {
    id: '28',
    name: 'Wheat Flour 5kg',
    brand: 'Aashirvaad',
    category: 'grocery',
    price: 250,
    rating: 4.6,
    reviews: 540,
    deliveryTime: 25,
    image: require('@/assets/ProductImage/sarash milk.avif'),
    description: 'High quality wheat flour',
    warranty: null,
    returnDays: 7,
  },
  {
    id: '29',
    name: 'Cooking Oil 1L',
    brand: 'Fortune',
    category: 'grocery',
    price: 180,
    rating: 4.4,
    reviews: 690,
    deliveryTime: 22,
    image: require('@/assets/ProductImage/red-bull.avif'),
    description: 'Refined cooking oil',
    warranty: null,
    returnDays: 5,
  },
  {
    id: '30',
    name: 'Milk 1L',
    brand: 'Amul',
    category: 'grocery',
    price: 60,
    rating: 4.8,
    reviews: 1200,
    deliveryTime: 15,
    image: require('@/assets/ProductImage/sarash milk.avif'),
    description: 'Fresh milk',
    warranty: null,
    returnDays: 1,
  },
  {
    id: '31',
    name: 'Sugar 1kg',
    brand: 'Madhur',
    category: 'grocery',
    price: 45,
    rating: 4.3,
    reviews: 380,
    deliveryTime: 20,
    image: require('@/assets/ProductImage/Hand senitizer.jpg'),
    description: 'Refined sugar',
    warranty: null,
    returnDays: 7,
  },
  {
    id: '32',
    name: 'Salt 1kg',
    brand: 'Tata',
    category: 'grocery',
    price: 20,
    rating: 4.2,
    reviews: 290,
    deliveryTime: 18,
    image: require('@/assets/ProductImage/paracetamol.jpg'),
    description: 'Iodized salt',
    warranty: null,
    returnDays: 5,
  },
  {
    id: '33',
    name: 'Tea Powder',
    brand: 'Tata Tea',
    category: 'grocery',
    price: 150,
    rating: 4.6,
    reviews: 620,
    deliveryTime: 18,
    image: require('@/assets/ProductImage/Bru coffee.jpg'),
    description: 'Strong tea leaves',
    warranty: null,
    returnDays: 7,
  },
  {
    id: '34',
    name: 'Biscuits Pack',
    brand: 'Parle-G',
    category: 'grocery',
    price: 30,
    rating: 4.4,
    reviews: 780,
    deliveryTime: 15,
    image: require('@/assets/ProductImage/serum.webp'),
    description: 'Crunchy biscuits',
    warranty: null,
    returnDays: 7,
  },
  {
    id: '35',
    name: 'Maggi Noodles',
    brand: 'Nestle',
    category: 'grocery',
    price: 14,
    rating: 4.5,
    reviews: 1100,
    deliveryTime: 12,
    image: require('@/assets/ProductImage/red-bull.avif'),
    description: 'Instant noodles',
    warranty: null,
    returnDays: 3,
  },
  {
    id: '36',
    name: 'Toor Dal 1kg',
    brand: 'Tata Sampann',
    category: 'grocery',
    price: 140,
    rating: 4.5,
    reviews: 450,
    deliveryTime: 18,
    image: require('@/assets/ProductImage/CMF buds pro 2.jpg'),
    description: 'High protein pulses',
    warranty: null,
    returnDays: 7,
  },

  // ⚡ ELECTRONICS (10)
  {
    id: '37',
    name: 'Smartphone',
    brand: 'Redmi',
    category: 'electronics',
    price: 15000,
    rating: 4.5,
    reviews: 2100,
    deliveryTime: 30,
    image: require('@/assets/ProductImage/CMF buds pro 2.jpg'),
    description: 'Budget smartphone',
    warranty: '1 Year',
    returnDays: 14,
  },
  {
    id: '38',
    name: 'Bluetooth Earbuds',
    brand: 'Boat',
    category: 'electronics',
    price: 2000,
    rating: 4.4,
    reviews: 890,
    deliveryTime: 20,
    image: require('@/assets/ProductImage/CMF buds pro 2.jpg'),
    description: 'Wireless audio',
    warranty: '6 Months',
    returnDays: 14,
  },
  {
    id: '39',
    name: 'Smartwatch',
    brand: 'Noise',
    category: 'electronics',
    price: 3000,
    rating: 4.3,
    reviews: 640,
    deliveryTime: 18,
    image: require('@/assets/ProductImage/red-bull.avif'),
    description: 'Fitness tracking',
    warranty: '1 Year',
    returnDays: 14,
  },
  {
    id: '40',
    name: 'Laptop',
    brand: 'HP',
    category: 'electronics',
    price: 50000,
    rating: 4.6,
    reviews: 520,
    deliveryTime: 35,
    image: require('@/assets/ProductImage/paracetamol.jpg'),
    description: 'Work and gaming',
    warranty: '1 Year',
    returnDays: 30,
  },
  {
    id: '41',
    name: 'Power Bank',
    brand: 'Mi',
    category: 'electronics',
    price: 1200,
    rating: 4.4,
    reviews: 750,
    deliveryTime: 15,
    image: require('@/assets/ProductImage/serum.webp'),
    description: 'Fast charging',
    warranty: '6 Months',
    returnDays: 7,
  },
  {
    id: '42',
    name: 'LED TV',
    brand: 'Samsung',
    category: 'electronics',
    price: 30000,
    rating: 4.7,
    reviews: 480,
    deliveryTime: 40,
    image: require('@/assets/ProductImage/Bru coffee.jpg'),
    description: 'Smart TV',
    warranty: '2 Year',
    returnDays: 14,
  },
  {
    id: '43',
    name: 'Bluetooth Speaker',
    brand: 'JBL',
    category: 'electronics',
    price: 1800,
    rating: 4.5,
    reviews: 620,
    deliveryTime: 15,
    image: require('@/assets/ProductImage/Hand senitizer.jpg'),
    description: 'Portable speaker',
    warranty: '1 Year',
    returnDays: 14,
  },
  {
    id: '44',
    name: 'Electric Kettle',
    brand: 'Prestige',
    category: 'electronics',
    price: 900,
    rating: 4.3,
    reviews: 380,
    deliveryTime: 12,
    image: require('@/assets/ProductImage/sarash milk.avif'),
    description: 'Boil water quickly',
    warranty: '1 Year',
    returnDays: 7,
  },
  {
    id: '45',
    name: 'Iron',
    brand: 'Philips',
    category: 'electronics',
    price: 1100,
    rating: 4.2,
    reviews: 290,
    deliveryTime: 14,
    image: require('@/assets/ProductImage/red-bull.avif'),
    description: 'Clothes ironing',
    warranty: '1 Year',
    returnDays: 7,
  },
  {
    id: '46',
    name: 'Mixer Grinder',
    brand: 'Bajaj',
    category: 'electronics',
    price: 3500,
    rating: 4.4,
    reviews: 550,
    deliveryTime: 18,
    image: require('@/assets/ProductImage/paracetamol.jpg'),
    description: 'Kitchen appliance',
    warranty: '2 Year',
    returnDays: 14,
  },

  // 👶 BABY PRODUCTS (10)
  {
    id: '47',
    name: 'Baby Diapers Pack',
    brand: 'Pampers',
    category: 'baby',
    price: 499,
    rating: 4.6,
    reviews: 920,
    deliveryTime: 15,
    image: require('@/assets/ProductImage/CMF buds pro 2.jpg'),
    description: 'Soft and absorbent',
    warranty: null,
    returnDays: 7,
  },
  {
    id: '48',
    name: 'Baby Wipes',
    brand: 'Huggies',
    category: 'baby',
    price: 199,
    rating: 4.5,
    reviews: 680,
    deliveryTime: 12,
    image: require('@/assets/ProductImage/Hand senitizer.jpg'),
    description: 'Gentle cleaning',
    warranty: null,
    returnDays: 7,
  },
  {
    id: '49',
    name: 'Baby Shampoo',
    brand: "Johnson's",
    category: 'baby',
    price: 180,
    rating: 4.4,
    reviews: 540,
    deliveryTime: 10,
    image: require('@/assets/ProductImage/serum.webp'),
    description: 'Tear-free formula',
    warranty: null,
    returnDays: 14,
  },
  {
    id: '50',
    name: 'Baby Lotion',
    brand: 'Himalaya',
    category: 'baby',
    price: 220,
    rating: 4.5,
    reviews: 620,
    deliveryTime: 12,
    image: require('@/assets/ProductImage/Bru coffee.jpg'),
    description: 'Moisturizes baby skin',
    warranty: null,
    returnDays: 14,
  },
  {
    id: '51',
    name: 'Baby Powder',
    brand: "Johnson's",
    category: 'baby',
    price: 150,
    rating: 4.4,
    reviews: 480,
    deliveryTime: 10,
    image: require('@/assets/ProductImage/sarash milk.avif'),
    description: 'Keeps skin dry',
    warranty: null,
    returnDays: 7,
  },
  {
    id: '52',
    name: 'Baby Feeding Bottle',
    brand: 'Philips Avent',
    category: 'baby',
    price: 250,
    rating: 4.5,
    reviews: 380,
    deliveryTime: 12,
    image: require('@/assets/ProductImage/red-bull.avif'),
    description: 'Safe feeding bottle',
    warranty: '1 Year',
    returnDays: 14,
  },
  {
    id: '53',
    name: 'Baby Oil',
    brand: 'Dabur',
    category: 'baby',
    price: 210,
    rating: 4.6,
    reviews: 720,
    deliveryTime: 10,
    image: require('@/assets/ProductImage/paracetamol.jpg'),
    description: 'Massage oil',
    warranty: null,
    returnDays: 7,
  },
  {
    id: '54',
    name: 'Baby Soap',
    brand: 'Sebamed',
    category: 'baby',
    price: 90,
    rating: 4.3,
    reviews: 340,
    deliveryTime: 10,
    image: require('@/assets/ProductImage/Hand senitizer.jpg'),
    description: 'Gentle cleansing',
    warranty: null,
    returnDays: 7,
  },
  {
    id: '55',
    name: 'Baby Blanket',
    brand: 'Mee Mee',
    category: 'baby',
    price: 600,
    rating: 4.5,
    reviews: 280,
    deliveryTime: 15,
    image: require('@/assets/ProductImage/CMF buds pro 2.jpg'),
    description: 'Soft and warm',
    warranty: null,
    returnDays: 14,
  },
  {
    id: '56',
    name: 'Baby Toy Set',
    brand: 'Fisher Price',
    category: 'baby',
    price: 350,
    rating: 4.4,
    reviews: 420,
    deliveryTime: 15,
    image: require('@/assets/ProductImage/serum.webp'),
    description: 'Safe toys for infants',
    warranty: '1 Year',
    returnDays: 14,
  },
];

// Get product by ID
export const getProductById = (id: string): Product | undefined => {
  return PRODUCTS.find(product => product.id === id);
};

// Get trending products (First 5)
export const MOCK_TRENDING_PRODUCTS = PRODUCTS.slice(0, 5);

// Get best sellers (Products from different categories)
export const MOCK_BEST_SELLERS = PRODUCTS.slice(5, 12);
